apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui2
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui2
  template:
    metadata:
      labels:
        app: guestbook-ui2
    spec:
      containers:
      - image: hub.iflytek.com/medical/centos-tomcat:8.5.40
        name: guestbook-ui2
        ports:
        - containerPort: 80
